import { INSIGHT_TYPE_LABELS, TASK_PRIORITY_LABELS } from "@/lib/constants";
import type { LearningSession, KeyInsight, SourceTask, LearningSource } from "@/lib/types";
import { getSourceProgress } from "./sourceProgress";

export function exportLearningReportToMarkdown(
  sources: LearningSource[],
  sessions: LearningSession[],
  insights: KeyInsight[],
  tasks: SourceTask[],
  userName: string = "Learner"
): void {
  const exportDate = new Date().toLocaleDateString("id-ID", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const lines: string[] = [];

  lines.push(`# Learning OS Report: ${userName}`);
  lines.push(`Dicetak pada: ${exportDate}`);
  lines.push("");

  // 1. Overall Stats
  lines.push("## 📊 Ringkasan Statistik", "");
  const totalMinutes = sessions.reduce((s, ses) => s + ses.durationMinutes, 0);
  lines.push(`- **Total Waktu Belajar:** ${Math.round(totalMinutes / 60)} jam (${totalMinutes} menit)`);
  lines.push(`- **Total Sesi:** ${sessions.length}`);
  lines.push(`- **Total Insight Tersimpan:** ${insights.length}`);
  lines.push(`- **Action Items Selesai:** ${tasks.filter(t => t.status === 'done').length}`);
  lines.push(`- **Sumber Belajar Aktif:** ${sources.length}`);
  lines.push("");

  // 2. Active Sources
  lines.push("## 📚 Sumber Belajar & Progres", "");
  for (const src of sources) {
    const sp = getSourceProgress(src);
    lines.push(`### ${src.title}`);
    lines.push(`- **Kreator:** ${src.creatorName}`);
    lines.push(`- **Progres:** ${sp.pct}% (${sp.consumed}/${sp.total} ${sp.unitLabel})`);
    lines.push(`- **Status:** ${src.status}`);
    lines.push("");
  }

  // 3. Recent Insights
  lines.push("## 💡 Insights Terbaru", "");
  const recentInsights = [...insights].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 10);
  for (const ins of recentInsights) {
    const type = INSIGHT_TYPE_LABELS[ins.type ?? "insight"];
    lines.push(`- **[${type}]** ${ins.quote}`);
    if (ins.reflection) lines.push(`  > *Refleksi: ${ins.reflection}*`);
  }
  lines.push("");

  // 4. Pending Tasks
  lines.push("## ✅ Action Items (Pending)", "");
  const pendingTasks = tasks.filter(t => t.status !== 'done' && t.status !== 'cancelled');
  for (const t of pendingTasks) {
    const prio = TASK_PRIORITY_LABELS[t.priority];
    lines.push(`- [ ] **[${prio}]** ${t.description}`);
  }
  lines.push("");

  lines.push("---");
  lines.push("*Generated by SkillFlow Learning OS*");

  const blob = new Blob([lines.join("\n")], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `skillflow-report-${new Date().toISOString().slice(0, 10)}.md`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 100);
}
